In [1]:
# Import dependencies
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [2]:
restaurant_df=pd.read_csv('./data/kayak_data_v04-2.csv')

restaurant_df.head()

,name,locality,cuisine,price_per_person,overall_rating,food,service,ambiance,reviews,noise,dining_style,latitude,longitude,url
0,Broadstone Bar & Kitchen,Financial District,American,$,4.2,4.1,4.1,4.1,268,Moderate,Casual Dining,40.704115,-74.011729,https://www.kayak.com/New-York-Restaurants-Bro...
1,Stone Street Tavern,Financial District,American,$,4.5,4.4,4.5,4.2,75,Moderate,Casual Dining,40.704278,-74.010273,https://www.kayak.com/New-York-Restaurants-Sto...
2,Industry Kitchen,Financial District,American,$,4.5,4.3,4.4,4.5,440,Moderate,Casual Dining,40.704921,-74.004874,https://www.kayak.com/New-York-Restaurants-Ind...
3,The Ketch - NYC,Financial District,Contemporary American,$,4.0,3.9,3.9,3.8,534,Moderate,Casual Elegant,40.706306,-74.007466,https://www.kayak.com/New-York-Restaurants-The...
4,The Tuck Room- New York,Financial District,Unspecified,$,4.2,4.1,4.1,4.4,1163,Moderate,Casual Elegant,40.706629,-74.003141,https://www.kayak.com/New-York-Restaurants-The...

In [3]:
restaurant_df=restaurant_df.reset_index()
restaurant_df=restaurant_df.reset_index(drop=True).rename(columns={'index':'restaurant_id'})
restaurant_df.head()

,restaurant_id,name,locality,cuisine,price_per_person,overall_rating,food,service,ambiance,reviews,noise,dining_style,latitude,longitude,url
0,0,Broadstone Bar & Kitchen,Financial District,American,$,4.2,4.1,4.1,4.1,268,Moderate,Casual Dining,40.704115,-74.011729,https://www.kayak.com/New-York-Restaurants-Bro...
1,1,Stone Street Tavern,Financial District,American,$,4.5,4.4,4.5,4.2,75,Moderate,Casual Dining,40.704278,-74.010273,https://www.kayak.com/New-York-Restaurants-Sto...
2,2,Industry Kitchen,Financial District,American,$,4.5,4.3,4.4,4.5,440,Moderate,Casual Dining,40.704921,-74.004874,https://www.kayak.com/New-York-Restaurants-Ind...
3,3,The Ketch - NYC,Financial District,Contemporary American,$,4.0,3.9,3.9,3.8,534,Moderate,Casual Elegant,40.706306,-74.007466,https://www.kayak.com/New-York-Restaurants-The...
4,4,The Tuck Room- New York,Financial District,Unspecified,$,4.2,4.1,4.1,4.4,1163,Moderate,Casual Elegant,40.706629,-74.003141,https://www.kayak.com/New-York-Restaurants-The...

In [4]:
connection=sqlite3.connect('./data/kayak_data.sqlite')

In [5]:
restaurant_df.to_sql('restaurants',connection,if_exists='replace',index=False, dtype={'restaurant_id': 'INTEGER PRIMARY KEY AUTOINCREMENT'})

711

In [6]:
connection.close()